# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PDFGeneratorDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PDFGeneratorDemo
pod 'PDFGenerator', '~> 3.0'

end
